on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: 'Trigger: Push action'
jobs:
  write_good_job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: A job to lint Markdown files
    steps:
    - uses: actions/checkout@v4

    - name: install prereqs
      run: sudo apt-get install python3-proselint

    - name: create proselint config
      run: |
        cat <<JSON > $HOME/.proselintrc
        {
          "checks": {
            "typography.diacritical_marks": false,
            "typography.symbols": false,
            "annotations.misc": false
          }
        }
        JSON
    - name: check prose
      id: write-good
      run: a=`git ls-files '*.md' | grep -v docs/CHECKSRC.md` && proselint $a README

    - name: Get the write-good output
      run: echo "${{ steps.write-good.outputs.result }}"

    - name: Post comment
      uses: mshick/add-pr-comment@v1
      if: ${{ steps.write-good.outputs.result }}
      with:
        message: |
          ${{ steps.write-good.outputs.result }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: false # This is the default